name: DeShawn Marie
favicon: null
layout_spectrum: 0.9124448990914971
typography_spectrum: 0.12372147873975337
title: DeShawn Marie Handmade Soap
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8912926875054836
  lightness: 0.8327737976796925
  saturation: 0.9742009099572897
  rhythmicContrast: 0.007997314678505063
purpose: []
