name: DeShawn Marie
favicon: null
layout_spectrum: 0.99913
typography_spectrum: 0.12372147873975337
title: DeShawn Marie Handmade Soap
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7e3c07'
    - '#d26f58'
    - '#aeb0b1'
    - '#da8e7b'
  brandStrength: 0.75
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0.007997314678505063
purpose: []
